# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fugint de l'Escalímpal
email: joana.borsch@escalipal.com
description: Teatre i pensament
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://escalimpal.com" # the base hostname & protocol for your site, e.g. http://example.com
icon: /assets/images/icon-512.png
twitter_username: escalimpal
github_username: escalimpal
lang: ca
date_locale: ca

hide_search: true
# Build settings
markdown: kramdown
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts

plugins:
  - jekyll-paginate-v2
  - jekyll-date-localization

pagination:
  enabled: true
  per_page: 3
  permalink: "/page:num/"
  title: " - :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true

livereload: true
port: 8080
